config/routes.rb
Izebrg::Application.routes.draw do
  
  match '/auth/:provider/callback', to: 'authentications#create'
  resources :authentications

  root to: 'pages#home'
  match '/tou', to: 'pages#tou', as: 'tou'
  match '/help', to: 'pages#help', as: 'help'
  match '/about', to: 'pages#about', as: 'about'
  match '/contact', to: 'pages#contact', as: 'contact'

  devise_for :users, controllers: { registrations: 'registrations' }
  
    

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :user_id, :provider, :uid
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :authentications

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation,
  	:remember_me, :confirmed_at
	

	def apply_omniauth(omniauth)
  		authentications.build(provider: omniauth['provider'], uid: omniauth['uid'])
	end

	def password_required?
  		(authentications.empty? || !password.blank?) && super
	end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    @title = "sign in"
    @authentications = current_user.authentications if current_user
  end

  def create
    #raise request.env["omniauth.auth"].to_yaml
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = "Authentication successful."
      redirect_to authentications_url
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to new_user_registration_url
      end
    end
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  	def home
      @users = User.all  	
  	end

  	def tou
 		@title = "terms of use"
  	end

	def help
 		@title = "help"
  	end

  	def about
  		@title = "about us"
  	end

  	def contact
  		@title = "contact us"
  	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	
	def create
  		super
  		session[:omniauth] = nil unless @user.new_record? 
	end

	private
  
  	def build_resource(*args)
    	super
    	if session[:omniauth]
      		@user.apply_omniauth(session[:omniauth])
      		@user.valid?
    	end
  	end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		base_title = "izebrg"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end

	def resource_name
    	:user
  	end

  	def resource
    	@resource ||= User.new
  	end

  	def devise_mapping
    	@devise_mapping ||= Devise.mappings[:user]
  	end

	def coming_soon
		"This section is under construction!"
	end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/authentications/index.html.erb
<% title %>
<% if @authentications %>
 <% unless @authentications.empty? %>
  <p><strong>You can sign in to this account using:</strong></p>
   <div class="authentications">
    <% for authentication in @authentications %>
     <div class="authentication">
      <%= image_tag "#{authentication.provider}_32.png", :size => "32x32" %>
      <div class="provider"><%= authentication.provider.titleize&crarr;   
      %></div>
      <div class="uid"><%= authentication.uid %></div>
       <%= link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication &crarr; 
      option?', :method => :delete, :class => "remove" %>
     </div>
     <% end %>
     <div class="clear"></div>
    </div>
   <% end %>
   <p><strong>Add another service to sign in with:</strong></p>
  <% else %>
  <p><strong>Sign in through one of these services:</strong></p>
<% end %>

<a href="/auth/twitter" class="auth_provider">
  <%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %>Twitter</a>
<a href="/auth/facebook" class="auth_provider">
  <%= image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" %>Facebook</a>
<a href="/auth/google_apps" class="auth_provider">
  <%= image_tag "google_64.png", :size => "64x64", :alt => "Google" %>Google</a>
<a href="/auth/open_id" class="auth_provider">
  <%= image_tag "openid_64.png", :size => "64x64", :alt => "OpenID" %>OpenID</a>
<div class="clear"></div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to image_tag("twitter_32.png", alt: "twitter"), 'http://twitter.com/izebrg'%>
  </small>
  <nav>
    <ul>
      <li><%= link_to "about us",   about_path %></li>
      <li><%= link_to "contact", contact_path %></li>
      <li><%= link_to "help", help_path %></li>
      <li><%= link_to "terms of use", tou_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "izebrg", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "home",    root_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "#{current_user.email}", '#'%>
            <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "sign up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  		<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title><%= title %></title>
  		<%= stylesheet_link_tag    "application", :media => "all" %>
  		<%= javascript_include_tag "application" %>
  		<%= csrf_meta_tags %>
  		<%= render 'layouts/shim' %>
	</head>
	<body>
    	<%= render 'layouts/header' %>
    	<div class="container-fluid">
          <% flash.each do |key, value| %>
            <div class='flash' id='<%= key %>'>
              <%= value %>
            </div>
          <% end %>
      		<%= yield %>
    	</div>
    	<%= render 'layouts/footer' %>
  	</body>
</html>

app/views/pages/about.html.erb
<div class="center hero-unit">
	<h1>about izebrg</h1>

  	<h2>There's more to it than meets the eye!</h2>

  	<p><%= coming_soon %></p>
</div>

app/views/pages/contact.html.erb
<div class="center hero-unit">
	<h1>contact us</h1>

  	<h2>There's more to it than meets the eye!</h2>

  	<p><%= coming_soon %></p>
</div>

app/views/pages/help.html.erb
<div class="center hero-unit">
	<h1>help</h1>

  	<h2>There's more to it than meets the eye!</h2>

  	<p><%= coming_soon %></p>
</div>


app/views/pages/home.html.erb
<% if current_user %>
	<% span1 = "span12" %>
<% else %>
	<% span1 = "span8" %>
<% end %>
<div class="row-fluid hero-unit">
	<div class="<%= span1 %>">
		<div class="center">
			<h2>There's more to it than meets the eye!</h2>
			<% if !current_user %>
				<%= link_to "sign up!", new_user_registration_path, class: "btn btn-large btn-primary" %><br /><br />
				<h2>or</h2>
				<p>Connect using one of your existing accounts!</p>
				<%= link_to image_tag("twitter_64.png", alt: "twitter"),
					'/auth/twitter'%>
				<%= link_to image_tag("facebook_64.png", alt: "facebook"),
					'/auth/facebook'%>
					
			<% end %>
		</div>
	</div>
	<% if !current_user %>
	<div class="span3">
		<div class="row-fluid">
			<%= render 'shared/sign_in_form' %>
		</div>
	</div>
	<% end %>
</div>
	

app/views/pages/tou.html.erb
<div class="center hero-unit">
	<h1>terms of use</h1>

  	<h2>Just be good!</h2>

  	<p><%= coming_soon %></p>
</div>

app/views/shared/_sign_in_form.html.erb
<%= form_for(resource, :as => resource_name,
	:url => session_path(resource_name), html: {class: "well"}) do |f| %>
	<%= f.label(:email)%>
	<%= f.email_field(:email, class: 'span', placeholder: 'Your email') %>
	<%= f.label(:password)%>
	<%= f.password_field(:password, class: 'password', placeholder: 'Password' ) %>

	<% if devise_mapping.rememberable? -%>
		<div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
	<% end -%>

	<%= f.submit("sign in", html: { class: "btn btn-large btn-primary" }) %><br />
	<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  		<%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
	<% end -%>
<% end %>
